<template>
  <v-card>
    <v-footer
      app
      padless
    >
      <v-card
        flat
        tile
        width="100%"
        class="text-center"
      >
        <v-card-text>
          Jackson Lauder - {{ new Date().getFullYear() }}
        </v-card-text>
      </v-card>
    </v-footer>
  </v-card>
</template>
